import streamlit as st
import pandas as pd
import plotly.express as px

class AnomalyDetection:

    def __init__(self):
        """Initializes the alert page"""
        if "alerts" not in st.session_state:
            st.session_state.alerts = []
        print("Alert")
        
        self.render()
    def render(self):
        """Render the alert page UI"""
        st.title("🚨 Alert Center")
        st.write("Real-time anomaly alerts generated by the system")

        # Load session alerts
        alerts = st.session_state.alerts

        # If no alerts exist
        if len(alerts) == 0:
            st.info("No alerts yet. Monitoring...")
            return

        df = pd.DataFrame(alerts)

        # Convert timestamp to datetime
        if "timestamp" in df:
            df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

        # ------------------------
        # Summary Cards
        # ------------------------
        self.render_summary(df)

        st.markdown("---")

        # ------------------------
        # Alert Table
        # ------------------------
        self.render_table(df)

        st.markdown("---")

        # ------------------------
        # Charts
        # ------------------------
        self.render_charts(df)

        st.markdown("---")

        # ------------------------
        # Export Button
        # ------------------------
        self.render_export(df)

    # -------------------------------------------------------------------
    # SUMMARY SECTION
    # -------------------------------------------------------------------
    def render_summary(self, df):
        col1, col2, col3 = st.columns(3)

        col1.metric("Total Alerts", len(df))
        col2.metric(
            "Critical Alerts",
            df[df["severity"] == "critical"].shape[0] if "severity" in df else "N/A"
        )
        col3.metric("Unique Processes", df["process"].nunique())

    # -------------------------------------------------------------------
    # ALERT TABLE
    # -------------------------------------------------------------------
    def render_table(self, df):
        st.subheader("📄 Alert Logs")

        columns = ["timestamp", "process", "dst_port", "score"]
        if "severity" in df:
            columns.append("severity")

        st.dataframe(
            df[columns],
            use_container_width=True,
            hide_index=True
        )

    # -------------------------------------------------------------------
    # CHARTS SECTION
    # -------------------------------------------------------------------
    def render_charts(self, df):
        st.subheader("📊 Alert Analytics")

        chart1, chart2 = st.columns(2)

        # Top alert-generating processes
        with chart1:
            self.chart_top_processes(df)

        # Severity Pie Chart
        with chart2:
            self.chart_severity(df)

        # Timeline chart across full width
        st.write("📈 Alerts Over Time")
        self.chart_timeline(df)

    # ------------ chart: top processes ------------
    def chart_top_processes(self, df):
        st.write("🔝 Top Alerted Processes")

        top_proc = df["process"].value_counts().reset_index()
        top_proc.columns = ["process", "count"]

        fig = px.bar(top_proc, x="process", y="count", title="Process with Most Alerts")
        st.plotly_chart(fig, use_container_width=True)

    # ------------ chart: severity pie ------------
    def chart_severity(self, df):
        st.write("🧯 Alert Severity Breakdown")

        if "severity" not in df:
            st.info("Severity info is not available.")
            return

        fig = px.pie(df, names="severity", title="Severity Distribution")
        st.plotly_chart(fig, use_container_width=True)

    # ------------ chart: timeline ------------
    def chart_timeline(self, df):
        if "timestamp" not in df:
            st.info("Timestamp missing.")
            return

        timeline = df.groupby(
            df["timestamp"].dt.floor("min")
        ).size().reset_index(name="count")

        fig = px.line(
            timeline,
            x="timestamp",
            y="count",
            markers=True,
            title="Alert Timeline (alerts per minute)"
        )
        st.plotly_chart(fig, use_container_width=True)

    # -------------------------------------------------------------------
    # EXPORT SECTION
    # -------------------------------------------------------------------
    def render_export(self, df):
        st.download_button(
            label="💾 Download Alert Logs (CSV)",
            data=df.to_csv(index=False).encode(),
            file_name="alert_logs.csv",
            mime="text/csv"
        )
